### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by apsolut** [strangerstudios/pmpro-vat-tax#4] opened 2016-03-30 16:05 UTC
1. Stripe work only if user enable/set "**Show Billing Address Fields:YES**" , and it dont work if user set that field as "No" ... This isnt required by Stripe...
2. Croatia need to be inside "EU" countries - $pmpro_european_union = array().. missing "HR"...
3. $pmpro_european_union = array()... I18n - right now not usable/translatable via WPML or others...
4. Need to fix "Greece" - first array is "GR" and in second one is "EL"  -> "Greece" 
   so its not working right now...

**Comment by meserlian** [comment] 2017-02-10 13:37
Has anyone looked into these issues?

**Comment by bradydan** [comment] 2017-03-22 16:17
Is this being looked at?

**Comment by strangerstudios** [comment] 2017-03-22 16:18
1. While this isn't required by Stripe, the EU VAT rules require 2 forms of country identification. Until we get an GeoIP check in place, you'll need to ask user's their billing address as one of the forms of checking.

2. Croatia has been added. Thanks.

3. I'll test again, but I believe that it's all ready for translation. We just don't have translation packs for it yet.

4. We check for both. But let us know if something breaks because of this. https://github.com/strangerstudios/pmpro-vat-tax/blob/master/pmpro-vat-tax.php#L304

**Comment by bradydan** [comment] 2017-03-22 16:21
Thanks 👍 

Is the main issue being fixed too (can't make Stripe payemtn / register as member without entering a valid VAT number)?

Any ETA?

**Comment by strangerstudios** [comment] 2017-03-22 17:06
Do you mean #1 here? Our plan is to not fix that and require you use also get a billing address. I can take a moment to make sure it works (at your own risk of not being compliant) in case it's a quick fix.

Or is there another issue with Stripe + VAT. You should be able to pay the vat instead of using a vat number.

**Comment by bradydan** [comment] 2017-03-22 17:25
It's not a Stripe issue. I am referring to this issue: https://www.paidmembershipspro.com/forums/topic/vat-plugin-not-working/

Summary: when the VAT plugin is enabled, a valid VAT number must be entered, otherwise on submitting the form the registration page simply redirects back to itself 

It was [acknowledged that a bug exists](https://www.paidmembershipspro.com/forums/topic/vat-plugin-not-working/#post-99646)

Is this being worked on? Do I need to raise a new issue on GitHub?

**Comment by greathmaster** [comment] 2017-03-23 05:20
If someone has checked the VAT number checkbox, but fails to enter a VAT number and attempts to checkout it assumes they forgot and stops the checkout. Similarly, if they check the VAT number box and enter an invalid VAT number (and don't use the "Apply" button) it stops the checkout.

Previously we would just stop the checkout, which is what I believe is happening in that thread. We're in the process of adding better error messages so in each case the customer knows why the checkout failed.

**Comment by bradydan** [comment] 2017-03-23 07:59
Please read the linked forum post, which I included in my previous comment https://www.paidmembershipspro.com/forums/topic/vat-plugin-not-working/

The issue is that if the VAT checkbox is left **unchecked**, the form fails. The VAT plugin is unusable until that is fixed. For myself and others, this is a serious problem.

**Comment by strangerstudios** [comment] 2017-04-07 20:58
These issues are fixed for me, so closing the issue. Make sure you're running the latest version of the plugin and also collecting the full billing address.

**Closed by strangerstudios** 2017-04-07 20:58 UTC
